#!/bin/sh
set -e

# Project info
PROJECTNAME="xmlm"
VERSION="1.0.0"
COPYRIGHTYEAR="2007-2008"
EMAIL="daniel.buenzl i\\\@erratique.ch"

INSTALLDIR=${INSTALLDIR:="`ocamlc -where`/$PROJECTNAME"}
DOCDIR=${DOCDIR:="doc"}

# Caml tools
OCAMLDOC=${OCAMLDOC:="ocamldoc"}
OCAMLBUILD=${OCAMLBUILD:="ocamlbuild"}
BUILDFLAGS="-classic-display -cflags -g,-dtypes -Is test,src"

# Misc tools
CP=${CP:="cp"}
RM=${RM:="rm"}
MKDIR=${MKDIR:="mkdir"}

ocb () { $OCAMLBUILD $BUILDFLAGS $* ; }

action () 
{
  case $1 in
    module) 
      ocb $PROJECTNAME.cmx $PROJECTNAME.cmo ;;
    xmltrip) 
      ocb xmltrip.native ;;
    doc)
      ocb $PROJECTNAME.cmi
      $OCAMLDOC -html -I src -colorize-code -d $DOCDIR src/$PROJECTNAME.mli ;;
    distrib) distrib ;;
    install)
      action module
      $MKDIR -p $INSTALLDIR
      $CP _build/src/*.{ml,mli,cmi,cmo,cmx,o} $INSTALLDIR ;;
    clean) 
      ocb -clean ;;
    clean-all) 
      action clean
      rm -f $DOCDIR/*.html ;;
    *) 
      ocb $1;;
  esac;
} 

distrib ()
{
  CD=${CD:="cd"}
  FIND=${FIND:="find"}
  GREP=${GREP:="grep"}
  TAR=${TAR:="tar"}

  DIRNAME=$PROJECTNAME-$VERSION
  ROOTDIR=/tmp/$DIRNAME
  $RM -rf $ROOTDIR
  $MKDIR -p $ROOTDIR
  $CP -r . $ROOTDIR
  $CD $ROOTDIR
  action clean-all

  $RM -rf _darcs
  $FIND $ROOTDIR \
    \( -name "*~" -o -name ".DS_Store" -o -name ".gdb_history" \) \
    -exec $RM {} ';'
  for file in `$FIND $ROOTDIR -type f -print`; do
    sed -i "" "s/%%VERSION%%/$VERSION/; \
               s/%%COPYRIGHTYEAR%%/$COPYRIGHTYEAR/; \
               s/%%EMAIL%%/$EMAIL/;" \
	$file
  done

  action module
  action xmltrip
  action examples.cmo
  action doc
  action clean

  $CD ..
  $TAR -cvjf $DIRNAME.tbz $DIRNAME
  $RM -r $DIRNAME
}

if [ $# -eq 0 ]; then action module ; else
  while [ $# -gt 0 ]; do action $1; shift ; done
fi


