#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META                
add lib src/xmlm.mli      
add lib src/xmlm.cmi
add lib src/xmlm.cmx
add lib src/xmlm.cma
add lib src/xmlm.a
add lib src/xmlm.cmxa
add lib src/xmlm.cmxs

add bin test/xmltrip 

add doc README.md
add doc CHANGES.md
add doc test/examples.ml examples.ml
add doc test/xhtml.ml xhtml.ml

build
install xmlm
